#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { logger } = require("log-instance");

const APP_DIR = path.join(__dirname, "..", "..");
const LOCAL_DIR = path.join(APP_DIR, "local");
const SRC_DIR = path.join(APP_DIR, "src");
const EBT_DATA_DIR = path.join(LOCAL_DIR, "ebt-data");
const EBT_AUTHOR = path.join(EBT_DATA_DIR, "_author.json");
const EBT_PUBV2 = path.join(EBT_DATA_DIR, "_publication-v2.json");
const SCRIPT = path.basename(__filename);
const AUTHORS_PATH = path.join(SRC_DIR, "auto", "authors-v2.mjs");
const { Examples } = require(path.join(APP_DIR, 'index.js'));

const COMMENT = [`Auto-generated by ${SCRIPT}`];

logger.logLevel = "info";

(async function authors() {
  const msg = "authors() ";
  try {
    let langs = await fs.promises.readdir(path.join(EBT_DATA_DIR, 'translation'));
    let authorLangs = {};
    for (let i=0; i < langs.length; i++) {
      let lang = langs[i];
      let langPath = path.join(EBT_DATA_DIR, 'translation', lang);
      let authors = await fs.promises.readdir(langPath);
      for (let j=0; j < authors.length; j++) {
        let author = authors[j];
        authorLangs[author] = authorLangs[author]
          ? [lang, ...authorLangs[author]]
          : [lang];
      }
    }
    let ebtPubs = JSON.parse(await fs.promises.readFile(EBT_PUBV2));
    let pubAuthors = ebtPubs.reduce((a,v)=>{
      let { source_url, creator_uid, creator_name } = v;
      let src = source_url.split('/').slice(7,10);
      let [ type, lang, author ] = src;
      let exampleVersion = 0;
      let name = creator_name instanceof Array
        ? creator_name 
        : [ creator_name.toString() ];
      let key = `${lang}:${author}`;
      let info = a[key] = a[key] || {
        type,
        lang, 
        author, 
        name,
        exampleVersion,
      };
      name.forEach(v=>{
        if (!info.name.includes(v)) {
          info.name.push(v);
        }
      });
      return a;
    }, {});
    Object.keys(pubAuthors).forEach(key => {
      let pa = pubAuthors[key];
      let authoredExample = Examples.authors
        .filter(ea => ea.author === pa.author)[0];
      if (authoredExample) {
        pa.category = authoredExample.category instanceof Array
          ? authoredExample.category
          : [ authoredExample.category ].sort();
        pa.exampleVersion = Number(authoredExample.version);
      } else if (key === 'pli:ms') {
        pa.exampleVersion = 999999;
      }
    });

    let authorJson = JSON.stringify(pubAuthors, null, 2) + '\n';
    let authorMjs = [
      'const AUTHORS = ' + authorJson,
      'export default AUTHORS;\n',
    ].join('\n');
    await fs.promises.writeFile(AUTHORS_PATH, authorMjs);
    logger.info(`${SCRIPT}: DONE => ${AUTHORS_PATH}`);
  } catch (e) {
    logger.warn(e);
  }
})();
