#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { logger } from "log-instance";
import * as module from "../../index.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const APP_DIR = path.join(__dirname, "..", "..");
const LOCAL_DIR = path.join(APP_DIR, "local");
const SRC_DIR = path.join(APP_DIR, "src");
const EBT_DATA_DIR = path.join(LOCAL_DIR, "ebt-data");
const EBT_AUTHOR = path.join(EBT_DATA_DIR, "_author.json");
const SCRIPT = path.basename(__filename);
const AUTHORS_PATH = path.join(SRC_DIR, "auto", "authors.mjs");
const { Examples } = module;

const COMMENT = [`Auto-generated by ${SCRIPT}`];

logger.logLevel = "info";

(async function () {
  try {
    let langs = await fs.promises.readdir(path.join(EBT_DATA_DIR, 'translation'));
    let authorLangs = {};
    for (let i=0; i < langs.length; i++) {
      let lang = langs[i];
      let langPath = path.join(EBT_DATA_DIR, 'translation', lang);
      let authors = await fs.promises.readdir(langPath);
      for (let j=0; j < authors.length; j++) {
        let author = authors[j];
        authorLangs[author] = authorLangs[author]
          ? [lang, ...authorLangs[author]]
          : [lang];
      }
    }
    let ebtAuthors = JSON.parse(await fs.promises.readFile(EBT_AUTHOR));
    Object.keys(ebtAuthors).forEach(auid => {
      let ea = ebtAuthors[auid];
      let authoredExample = Examples.authors
        .filter(ea => ea.author===auid)[0];
      ea.author = auid;
      if (authoredExample) {
        ea.category = authoredExample.category instanceof Array
          ? authoredExample.category
          : [ authoredExample.category ].sort();
        ea.lang = authoredExample.lang;
        ea.exampleVersion = Number(authoredExample.version);
      } else if (auid === 'ms') {
        ea.exampleVersion = 999999;
        ea.lang = 'pli';
        ea.author = 'ms';
        ea.category = ["sutta", "vinaya"].sort();
      } else {
        ea.exampleVersion = 0;
      }
      if (ea.lang == null) {
        let langs = authorLangs[ea.author];
        langs?.length && (ea.lang = langs[0]);
      }
    });

    let authorJson = JSON.stringify(ebtAuthors, null, 2) + '\n';
    let authorMjs = [
      'const AUTHORS = ' + authorJson,
      'export default AUTHORS;\n',
    ].join('\n');
    await fs.promises.writeFile(AUTHORS_PATH, authorMjs);
    logger.info(`${SCRIPT}: DONE => ${AUTHORS_PATH}`);
    //console.log(authorJson);
  } catch (e) {
    logger.warn(e);
  }
})();
