const AUTHORS = {
  "en:sujato": {
    "type": "translation",
    "lang": "en",
    "author": "sujato",
    "name": [
      "Bhikkhu Sujato"
    ],
    "exampleVersion": 1,
    "sutta": true,
    "vinaya": false,
    "examples": [
      "sutta"
    ],
    "stats": {
      "sutta": 4166,
      "sutta/an": 1408,
      "sutta/an/an1": 31,
      "sutta/an/an2": 19,
      "sutta/an/an3": 158,
      "sutta/an/an4": 278,
      "sutta/an/an5": 271,
      "sutta/an/an6": 125,
      "sutta/an/an7": 101,
      "sutta/an/an8": 96,
      "sutta/an/an9": 82,
      "sutta/an/an10": 211,
      "sutta/an/an11": 36,
      "sutta/kn": 753,
      "sutta/kn/cp": 35,
      "sutta/kn/dhp": 26,
      "sutta/dn": 34,
      "sutta/kn/iti": 112,
      "sutta/kn/iti/vagga1": 10,
      "sutta/kn/iti/vagga2": 10,
      "sutta/kn/iti/vagga3": 7,
      "sutta/kn/iti/vagga4": 10,
      "sutta/kn/iti/vagga5": 12,
      "sutta/kn/iti/vagga6": 10,
      "sutta/kn/iti/vagga7": 10,
      "sutta/kn/iti/vagga8": 10,
      "sutta/kn/iti/vagga9": 10,
      "sutta/kn/iti/vagga10": 10,
      "sutta/kn/iti/vagga11": 13,
      "sutta/kn/ja": 81,
      "sutta/kn/kp": 9,
      "sutta/mn": 152,
      "sutta/sn": 1819,
      "sutta/sn/sn1": 81,
      "sutta/sn/sn2": 30,
      "sutta/sn/sn3": 25,
      "sutta/sn/sn4": 25,
      "sutta/sn/sn5": 10,
      "sutta/sn/sn6": 15,
      "sutta/sn/sn7": 22,
      "sutta/sn/sn8": 12,
      "sutta/sn/sn9": 14,
      "sutta/sn/sn10": 12,
      "sutta/sn/sn11": 25,
      "sutta/sn/sn12": 75,
      "sutta/sn/sn13": 11,
      "sutta/sn/sn14": 39,
      "sutta/sn/sn15": 20,
      "sutta/sn/sn16": 13,
      "sutta/sn/sn17": 31,
      "sutta/sn/sn18": 14,
      "sutta/sn/sn19": 21,
      "sutta/sn/sn20": 12,
      "sutta/sn/sn21": 12,
      "sutta/sn/sn22": 159,
      "sutta/sn/sn23": 26,
      "sutta/sn/sn24": 35,
      "sutta/sn/sn25": 10,
      "sutta/sn/sn26": 10,
      "sutta/sn/sn27": 10,
      "sutta/sn/sn28": 10,
      "sutta/sn/sn29": 12,
      "sutta/sn/sn30": 6,
      "sutta/sn/sn31": 6,
      "sutta/sn/sn32": 9,
      "sutta/sn/sn33": 16,
      "sutta/sn/sn34": 27,
      "sutta/sn/sn35": 201,
      "sutta/sn/sn36": 31,
      "sutta/sn/sn37": 34,
      "sutta/sn/sn38": 16,
      "sutta/sn/sn39": 2,
      "sutta/sn/sn40": 11,
      "sutta/sn/sn41": 10,
      "sutta/sn/sn42": 13,
      "sutta/sn/sn43": 15,
      "sutta/sn/sn44": 11,
      "sutta/sn/sn45": 114,
      "sutta/sn/sn46": 87,
      "sutta/sn/sn47": 55,
      "sutta/sn/sn48": 80,
      "sutta/sn/sn49": 5,
      "sutta/sn/sn50": 10,
      "sutta/sn/sn51": 37,
      "sutta/sn/sn52": 24,
      "sutta/sn/sn53": 5,
      "sutta/sn/sn54": 20,
      "sutta/sn/sn55": 74,
      "sutta/sn/sn56": 109,
      "sutta/kn/snp": 73,
      "sutta/kn/snp/vagga1": 12,
      "sutta/kn/snp/vagga2": 14,
      "sutta/kn/snp/vagga3": 12,
      "sutta/kn/snp/vagga4": 16,
      "sutta/kn/snp/vagga5": 19,
      "sutta/kn/thag": 264,
      "sutta/kn/thig": 73,
      "sutta/kn/ud": 80,
      "sutta/kn/ud/vagga1": 10,
      "sutta/kn/ud/vagga2": 10,
      "sutta/kn/ud/vagga3": 10,
      "sutta/kn/ud/vagga4": 10,
      "sutta/kn/ud/vagga5": 10,
      "sutta/kn/ud/vagga6": 10,
      "sutta/kn/ud/vagga7": 10,
      "sutta/kn/ud/vagga8": 10
    }
  },
  "en:brahmali": {
    "type": "translation",
    "lang": "en",
    "author": "brahmali",
    "name": [
      "Bhikkhu Brahmali"
    ],
    "exampleVersion": 0,
    "vinaya": true,
    "stats": {
      "vinaya": 427,
      "vinaya/pli-tv-bi-vb": 131,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-np": 12,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pc": 94,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pd": 2,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pj": 9,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-sk": 2,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-ss": 10,
      "vinaya/pli-tv-bu-vb": 221,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-ay": 2,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-np": 30,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pc": 92,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pd": 4,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pj": 4,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-sk": 75,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-ss": 13,
      "vinaya/pli-tv-kd": 22,
      "vinaya/pli-tv-pvr": 51
    }
  },
  "de:sabbamitta": {
    "type": "translation",
    "lang": "de",
    "author": "sabbamitta",
    "name": [
      "Sabbamitta"
    ],
    "exampleVersion": 1,
    "sutta": true,
    "vinaya": false,
    "examples": [
      "sutta"
    ],
    "stats": {
      "sutta": 4004,
      "sutta/an": 1408,
      "sutta/an/an1": 31,
      "sutta/an/an2": 19,
      "sutta/an/an3": 158,
      "sutta/an/an4": 278,
      "sutta/an/an5": 271,
      "sutta/an/an6": 125,
      "sutta/an/an7": 101,
      "sutta/an/an8": 96,
      "sutta/an/an9": 82,
      "sutta/an/an10": 211,
      "sutta/an/an11": 36,
      "sutta/kn": 637,
      "sutta/kn/cp": 34,
      "sutta/kn/dhp": 26,
      "sutta/dn": 34,
      "sutta/kn/iti": 112,
      "sutta/kn/iti/vagga1": 10,
      "sutta/kn/iti/vagga2": 10,
      "sutta/kn/iti/vagga3": 7,
      "sutta/kn/iti/vagga4": 10,
      "sutta/kn/iti/vagga5": 12,
      "sutta/kn/iti/vagga6": 10,
      "sutta/kn/iti/vagga7": 10,
      "sutta/kn/iti/vagga8": 10,
      "sutta/kn/iti/vagga9": 10,
      "sutta/kn/iti/vagga10": 10,
      "sutta/kn/iti/vagga11": 13,
      "sutta/kn/ja": 21,
      "sutta/kn/kp": 9,
      "sutta/kn/mil": 1,
      "sutta/mn": 106,
      "sutta/sn": 1819,
      "sutta/sn/sn1": 81,
      "sutta/sn/sn2": 30,
      "sutta/sn/sn3": 25,
      "sutta/sn/sn4": 25,
      "sutta/sn/sn5": 10,
      "sutta/sn/sn6": 15,
      "sutta/sn/sn7": 22,
      "sutta/sn/sn8": 12,
      "sutta/sn/sn9": 14,
      "sutta/sn/sn10": 12,
      "sutta/sn/sn11": 25,
      "sutta/sn/sn12": 75,
      "sutta/sn/sn13": 11,
      "sutta/sn/sn14": 39,
      "sutta/sn/sn15": 20,
      "sutta/sn/sn16": 13,
      "sutta/sn/sn17": 31,
      "sutta/sn/sn18": 14,
      "sutta/sn/sn19": 21,
      "sutta/sn/sn20": 12,
      "sutta/sn/sn21": 12,
      "sutta/sn/sn22": 159,
      "sutta/sn/sn23": 26,
      "sutta/sn/sn24": 35,
      "sutta/sn/sn25": 10,
      "sutta/sn/sn26": 10,
      "sutta/sn/sn27": 10,
      "sutta/sn/sn28": 10,
      "sutta/sn/sn29": 12,
      "sutta/sn/sn30": 6,
      "sutta/sn/sn31": 6,
      "sutta/sn/sn32": 9,
      "sutta/sn/sn33": 16,
      "sutta/sn/sn34": 27,
      "sutta/sn/sn35": 201,
      "sutta/sn/sn36": 31,
      "sutta/sn/sn37": 34,
      "sutta/sn/sn38": 16,
      "sutta/sn/sn39": 2,
      "sutta/sn/sn40": 11,
      "sutta/sn/sn41": 10,
      "sutta/sn/sn42": 13,
      "sutta/sn/sn43": 15,
      "sutta/sn/sn44": 11,
      "sutta/sn/sn45": 114,
      "sutta/sn/sn46": 87,
      "sutta/sn/sn47": 55,
      "sutta/sn/sn48": 80,
      "sutta/sn/sn49": 5,
      "sutta/sn/sn50": 10,
      "sutta/sn/sn51": 37,
      "sutta/sn/sn52": 24,
      "sutta/sn/sn53": 5,
      "sutta/sn/sn54": 20,
      "sutta/sn/sn55": 74,
      "sutta/sn/sn56": 109,
      "sutta/kn/snp": 17,
      "sutta/kn/snp/vagga1": 5,
      "sutta/kn/snp/vagga2": 6,
      "sutta/kn/snp/vagga3": 1,
      "sutta/kn/snp/vagga4": 2,
      "sutta/kn/snp/vagga5": 3,
      "sutta/kn/thag": 264,
      "sutta/kn/thig": 73,
      "sutta/kn/ud": 80,
      "sutta/kn/ud/vagga1": 10,
      "sutta/kn/ud/vagga2": 10,
      "sutta/kn/ud/vagga3": 10,
      "sutta/kn/ud/vagga4": 10,
      "sutta/kn/ud/vagga5": 10,
      "sutta/kn/ud/vagga6": 10,
      "sutta/kn/ud/vagga7": 10,
      "sutta/kn/ud/vagga8": 10
    }
  },
  "jpn:kaz": {
    "type": "translation",
    "lang": "jpn",
    "author": "kaz",
    "name": [
      "竹原 一江"
    ],
    "exampleVersion": 1,
    "sutta": true,
    "examples": [
      "sutta"
    ],
    "stats": {
      "sutta": 56,
      "sutta/an": 56,
      "sutta/an/an1": 31,
      "sutta/an/an2": 15,
      "sutta/an/an3": 5,
      "sutta/an/an4": 4,
      "sutta/an/an11": 1
    }
  },
  "pt:laera-quaresma": {
    "type": "translation",
    "lang": "pt",
    "author": "laera-quaresma",
    "name": [
      "Gabriel Laera",
      "Marco Quaresma",
      "Vitor Guimarães"
    ],
    "exampleVersion": 2,
    "sutta": true,
    "vinaya": false,
    "examples": [
      "sutta"
    ],
    "stats": {
      "sutta": 193,
      "sutta/an": 85,
      "sutta/an/an1": 21,
      "sutta/an/an2": 8,
      "sutta/an/an3": 48,
      "sutta/an/an4": 3,
      "sutta/an/an5": 4,
      "sutta/an/an7": 1,
      "sutta/kn": 10,
      "sutta/kn/kp": 9,
      "sutta/mn": 2,
      "sutta/sn": 96,
      "sutta/sn/sn1": 72,
      "sutta/sn/sn2": 23,
      "sutta/sn/sn5": 1,
      "sutta/kn/snp": 1,
      "sutta/kn/snp/vagga5": 1
    }
  },
  "en:soma": {
    "type": "translation",
    "lang": "en",
    "author": "soma",
    "name": [
      "Bhikkhuni Soma"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 73,
      "sutta/kn": 73,
      "sutta/kn/thig": 73
    }
  },
  "cs:ashinsarana": {
    "type": "translation",
    "lang": "cs",
    "author": "ashinsarana",
    "name": [
      "Ashin Saraṅa"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 276,
      "sutta/an": 276,
      "sutta/an/an4": 276
    }
  },
  "my:my-team": {
    "type": "translation",
    "lang": "my",
    "author": "my-team",
    "name": [
      "Nyein Chan Aye"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 4,
      "sutta/dn": 4
    }
  },
  "en:kovilo": {
    "type": "translation",
    "lang": "en",
    "author": "kovilo",
    "name": [
      "Kovilo Bhikkhu"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 2,
      "sutta/an": 1,
      "sutta/an/an4": 1,
      "sutta/kn": 1,
      "sutta/kn/pv": 1
    }
  },
  "pli:ms": {
    "type": "root",
    "lang": "pli",
    "author": "ms",
    "name": [
      "The M.L. Maniratana Bunnag Dhamma Society Fund"
    ],
    "exampleVersion": 999999,
    "sutta": true,
    "vinaya": true,
    "stats": {
      "sutta": 5764,
      "sutta/an": 1408,
      "sutta/an/an1": 31,
      "sutta/an/an2": 19,
      "sutta/an/an3": 158,
      "sutta/an/an4": 278,
      "sutta/an/an5": 271,
      "sutta/an/an6": 125,
      "sutta/an/an7": 101,
      "sutta/an/an8": 96,
      "sutta/an/an9": 82,
      "sutta/an/an10": 211,
      "sutta/an/an11": 36,
      "sutta/kn": 2351,
      "sutta/kn/cp": 35,
      "sutta/kn/dhp": 26,
      "sutta/dn": 34,
      "sutta/kn/iti": 112,
      "sutta/kn/iti/vagga1": 10,
      "sutta/kn/iti/vagga2": 10,
      "sutta/kn/iti/vagga3": 7,
      "sutta/kn/iti/vagga4": 10,
      "sutta/kn/iti/vagga5": 12,
      "sutta/kn/iti/vagga6": 10,
      "sutta/kn/iti/vagga7": 10,
      "sutta/kn/iti/vagga8": 10,
      "sutta/kn/iti/vagga9": 10,
      "sutta/kn/iti/vagga10": 10,
      "sutta/kn/iti/vagga11": 13,
      "sutta/kn/ja": 547,
      "sutta/kn/kp": 9,
      "sutta/kn/mil": 248,
      "sutta/mn": 152,
      "vinaya": 427,
      "vinaya/pli-tv-bi-vb": 131,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-np": 12,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pc": 94,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pd": 2,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-pj": 9,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-sk": 2,
      "vinaya/pli-tv-bi-vb/pli-tv-bi-vb-ss": 10,
      "vinaya/pli-tv-bu-vb": 221,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-ay": 2,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-np": 30,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pc": 92,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pd": 4,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-pj": 4,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-sk": 75,
      "vinaya/pli-tv-bu-vb/pli-tv-bu-vb-ss": 13,
      "vinaya/pli-tv-kd": 22,
      "vinaya/pli-tv-pvr": 51,
      "sutta/kn/pv": 51,
      "sutta/sn": 1819,
      "sutta/sn/sn1": 81,
      "sutta/sn/sn2": 30,
      "sutta/sn/sn3": 25,
      "sutta/sn/sn4": 25,
      "sutta/sn/sn5": 10,
      "sutta/sn/sn6": 15,
      "sutta/sn/sn7": 22,
      "sutta/sn/sn8": 12,
      "sutta/sn/sn9": 14,
      "sutta/sn/sn10": 12,
      "sutta/sn/sn11": 25,
      "sutta/sn/sn12": 75,
      "sutta/sn/sn13": 11,
      "sutta/sn/sn14": 39,
      "sutta/sn/sn15": 20,
      "sutta/sn/sn16": 13,
      "sutta/sn/sn17": 31,
      "sutta/sn/sn18": 14,
      "sutta/sn/sn19": 21,
      "sutta/sn/sn20": 12,
      "sutta/sn/sn21": 12,
      "sutta/sn/sn22": 159,
      "sutta/sn/sn23": 26,
      "sutta/sn/sn24": 35,
      "sutta/sn/sn25": 10,
      "sutta/sn/sn26": 10,
      "sutta/sn/sn27": 10,
      "sutta/sn/sn28": 10,
      "sutta/sn/sn29": 12,
      "sutta/sn/sn30": 6,
      "sutta/sn/sn31": 6,
      "sutta/sn/sn32": 9,
      "sutta/sn/sn33": 16,
      "sutta/sn/sn34": 27,
      "sutta/sn/sn35": 201,
      "sutta/sn/sn36": 31,
      "sutta/sn/sn37": 34,
      "sutta/sn/sn38": 16,
      "sutta/sn/sn39": 2,
      "sutta/sn/sn40": 11,
      "sutta/sn/sn41": 10,
      "sutta/sn/sn42": 13,
      "sutta/sn/sn43": 15,
      "sutta/sn/sn44": 11,
      "sutta/sn/sn45": 114,
      "sutta/sn/sn46": 87,
      "sutta/sn/sn47": 55,
      "sutta/sn/sn48": 80,
      "sutta/sn/sn49": 5,
      "sutta/sn/sn50": 10,
      "sutta/sn/sn51": 37,
      "sutta/sn/sn52": 24,
      "sutta/sn/sn53": 5,
      "sutta/sn/sn54": 20,
      "sutta/sn/sn55": 74,
      "sutta/sn/sn56": 109,
      "sutta/kn/snp": 73,
      "sutta/kn/snp/vagga1": 12,
      "sutta/kn/snp/vagga2": 14,
      "sutta/kn/snp/vagga3": 12,
      "sutta/kn/snp/vagga4": 16,
      "sutta/kn/snp/vagga5": 19,
      "sutta/kn/thag": 264,
      "sutta/kn/thig": 73,
      "sutta/kn/ud": 80,
      "sutta/kn/ud/vagga1": 10,
      "sutta/kn/ud/vagga2": 10,
      "sutta/kn/ud/vagga3": 10,
      "sutta/kn/ud/vagga4": 10,
      "sutta/kn/ud/vagga5": 10,
      "sutta/kn/ud/vagga6": 10,
      "sutta/kn/ud/vagga7": 10,
      "sutta/kn/ud/vagga8": 10,
      "sutta/kn/bv": 29,
      "sutta/kn/cnd": 23,
      "sutta/kn/mnd": 16,
      "sutta/kn/ne": 37,
      "sutta/kn/pe": 9,
      "sutta/kn/ps": 31,
      "sutta/kn/tha-ap": 563,
      "sutta/kn/thi-ap": 40,
      "sutta/kn/vv": 85
    }
  },
  "vi:phantuananh": {
    "type": "translation",
    "lang": "vi",
    "author": "phantuananh",
    "name": [
      "Bhikkhu Thích Minh Châu"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 26,
      "sutta/kn": 26,
      "sutta/kn/dhp": 26
    }
  },
  "fi:mudito": {
    "type": "translation",
    "lang": "fi",
    "author": "mudito",
    "name": [
      "Ajahn Mudito"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 1,
      "sutta/an": 1,
      "sutta/an/an1": 1
    }
  },
  "pl:hardao": {
    "type": "translation",
    "lang": "pl",
    "author": "hardao",
    "name": [
      "Piotr Jagodziński"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 56,
      "sutta/an": 18,
      "sutta/an/an3": 5,
      "sutta/an/an4": 7,
      "sutta/an/an5": 1,
      "sutta/an/an8": 2,
      "sutta/an/an10": 2,
      "sutta/an/an11": 1,
      "sutta/dn": 1,
      "sutta/kn": 6,
      "sutta/kn/kp": 2,
      "sutta/mn": 10,
      "sutta/sn": 21,
      "sutta/sn/sn12": 6,
      "sutta/sn/sn15": 2,
      "sutta/sn/sn16": 1,
      "sutta/sn/sn20": 1,
      "sutta/sn/sn22": 3,
      "sutta/sn/sn35": 2,
      "sutta/sn/sn36": 1,
      "sutta/sn/sn44": 1,
      "sutta/sn/sn45": 1,
      "sutta/sn/sn47": 2,
      "sutta/sn/sn51": 1,
      "sutta/kn/snp": 2,
      "sutta/kn/snp/vagga1": 1,
      "sutta/kn/snp/vagga2": 1,
      "sutta/kn/ud": 2,
      "sutta/kn/ud/vagga8": 2
    }
  },
  "en:suddhaso": {
    "type": "translation",
    "lang": "en",
    "author": "suddhaso",
    "name": [
      "Bhante Suddhāso"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 15,
      "sutta/kn": 15,
      "sutta/kn/dhp": 15
    }
  },
  "it:giovannizappa": {
    "type": "translation",
    "lang": "it",
    "author": "giovannizappa",
    "name": [
      "Giovanni Zappa"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 18,
      "sutta/mn": 18
    }
  },
  "lt:piyadassi": {
    "type": "translation",
    "lang": "lt",
    "author": "piyadassi",
    "name": [
      "Sayalay Piyadassi"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 313,
      "sutta/an": 62,
      "sutta/an/an1": 2,
      "sutta/an/an3": 4,
      "sutta/an/an4": 15,
      "sutta/an/an5": 11,
      "sutta/an/an6": 8,
      "sutta/an/an7": 7,
      "sutta/an/an8": 3,
      "sutta/an/an9": 5,
      "sutta/an/an10": 6,
      "sutta/an/an11": 1,
      "sutta/dn": 2,
      "sutta/kn": 105,
      "sutta/kn/iti": 99,
      "sutta/kn/iti/vagga1": 10,
      "sutta/kn/iti/vagga2": 10,
      "sutta/kn/iti/vagga3": 7,
      "sutta/kn/iti/vagga4": 10,
      "sutta/kn/iti/vagga5": 12,
      "sutta/kn/iti/vagga6": 10,
      "sutta/kn/iti/vagga7": 10,
      "sutta/kn/iti/vagga8": 10,
      "sutta/kn/iti/vagga9": 10,
      "sutta/kn/iti/vagga10": 10,
      "sutta/mn": 24,
      "sutta/sn": 120,
      "sutta/sn/sn1": 3,
      "sutta/sn/sn2": 1,
      "sutta/sn/sn11": 3,
      "sutta/sn/sn12": 8,
      "sutta/sn/sn15": 20,
      "sutta/sn/sn22": 17,
      "sutta/sn/sn35": 19,
      "sutta/sn/sn36": 1,
      "sutta/sn/sn45": 2,
      "sutta/sn/sn46": 23,
      "sutta/sn/sn47": 1,
      "sutta/sn/sn48": 1,
      "sutta/sn/sn49": 1,
      "sutta/sn/sn50": 1,
      "sutta/sn/sn51": 1,
      "sutta/sn/sn53": 1,
      "sutta/sn/sn54": 7,
      "sutta/sn/sn55": 2,
      "sutta/sn/sn56": 8,
      "sutta/kn/snp": 6,
      "sutta/kn/snp/vagga1": 1,
      "sutta/kn/snp/vagga2": 1,
      "sutta/kn/snp/vagga5": 4
    }
  },
  "gu:trush": {
    "type": "translation",
    "lang": "gu",
    "author": "trush",
    "name": [
      "तृषांत मजमुदार"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 9,
      "sutta/mn": 9
    }
  },
  "hi:trush": {
    "type": "translation",
    "lang": "hi",
    "author": "trush",
    "name": [
      "तृषांत मजमुदार"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 7,
      "sutta/mn": 7
    }
  },
  "sr:brankokovacevic": {
    "type": "translation",
    "lang": "sr",
    "author": "brankokovacevic",
    "name": [
      "Branislav Kovačević"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 209,
      "sutta/dn": 34,
      "sutta/mn": 12,
      "sutta/sn": 83,
      "sutta/sn/sn1": 50,
      "sutta/sn/sn5": 10,
      "sutta/sn/sn22": 10,
      "sutta/sn/sn35": 13,
      "sutta/kn": 80,
      "sutta/kn/ud": 80,
      "sutta/kn/ud/vagga1": 10,
      "sutta/kn/ud/vagga2": 10,
      "sutta/kn/ud/vagga3": 10,
      "sutta/kn/ud/vagga4": 10,
      "sutta/kn/ud/vagga5": 10,
      "sutta/kn/ud/vagga6": 10,
      "sutta/kn/ud/vagga7": 10,
      "sutta/kn/ud/vagga8": 10
    }
  },
  "fr:noeismet": {
    "type": "translation",
    "lang": "fr",
    "author": "noeismet",
    "name": [
      "Noé Ismet"
    ],
    "exampleVersion": 1,
    "sutta": true,
    "examples": [
      "sutta"
    ],
    "stats": {
      "sutta": 53,
      "sutta/an": 11,
      "sutta/an/an1": 1,
      "sutta/an/an3": 4,
      "sutta/an/an4": 2,
      "sutta/an/an7": 1,
      "sutta/an/an8": 2,
      "sutta/an/an11": 1,
      "sutta/dn": 4,
      "sutta/mn": 26,
      "sutta/sn": 12,
      "sutta/sn/sn3": 2,
      "sutta/sn/sn15": 4,
      "sutta/sn/sn22": 2,
      "sutta/sn/sn35": 1,
      "sutta/sn/sn42": 1,
      "sutta/sn/sn48": 1,
      "sutta/sn/sn56": 1
    }
  },
  "fr:sekha": {
    "type": "translation",
    "lang": "fr",
    "author": "sekha",
    "name": [
      "Rémy Zins"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 211,
      "sutta/an": 115,
      "sutta/an/an1": 31,
      "sutta/an/an2": 2,
      "sutta/an/an3": 57,
      "sutta/an/an10": 2,
      "sutta/an/an11": 23,
      "sutta/sn": 96,
      "sutta/sn/sn53": 1,
      "sutta/sn/sn54": 20,
      "sutta/sn/sn55": 47,
      "sutta/sn/sn56": 28
    }
  },
  "pl:marcinow": {
    "type": "translation",
    "lang": "pl",
    "author": "marcinow",
    "name": [
      "Piotr Marcinów"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 10,
      "sutta/sn": 10,
      "sutta/sn/sn56": 10
    }
  },
  "ru:sv": {
    "type": "translation",
    "lang": "ru",
    "author": "sv",
    "name": [
      "SV theravada.ru"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 376,
      "sutta/an": 5,
      "sutta/an/an5": 2,
      "sutta/an/an7": 1,
      "sutta/an/an9": 1,
      "sutta/an/an10": 1,
      "sutta/kn": 7,
      "sutta/kn/iti": 6,
      "sutta/kn/iti/vagga1": 1,
      "sutta/kn/iti/vagga3": 3,
      "sutta/kn/iti/vagga7": 1,
      "sutta/kn/iti/vagga10": 1,
      "sutta/mn": 152,
      "sutta/sn": 212,
      "sutta/sn/sn1": 81,
      "sutta/sn/sn2": 30,
      "sutta/sn/sn3": 25,
      "sutta/sn/sn4": 25,
      "sutta/sn/sn5": 10,
      "sutta/sn/sn6": 15,
      "sutta/sn/sn7": 22,
      "sutta/sn/sn12": 1,
      "sutta/sn/sn45": 3,
      "sutta/kn/snp": 1,
      "sutta/kn/snp/vagga1": 1
    }
  },
  "es:maggatr": {
    "type": "translation",
    "lang": "es",
    "author": "maggatr",
    "name": [
      "Magga Traducciones"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 9,
      "sutta/an": 5,
      "sutta/an/an2": 1,
      "sutta/an/an3": 2,
      "sutta/an/an8": 2,
      "sutta/mn": 1,
      "sutta/sn": 3,
      "sutta/sn/sn3": 2,
      "sutta/sn/sn36": 1
    }
  },
  "en:kelly": {
    "type": "translation",
    "lang": "en",
    "author": "kelly",
    "name": [
      "John Kelly"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 86,
      "sutta/kn": 86,
      "sutta/kn/mil": 86
    }
  },
  "ru:syrkin": {
    "type": "translation",
    "lang": "ru",
    "author": "syrkin",
    "name": [
      "A. Y. Syrkin"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 8,
      "sutta/dn": 8
    }
  },
  "ru:narinyanievmenenko": {
    "type": "translation",
    "lang": "ru",
    "author": "narinyanievmenenko",
    "name": [
      "Evgenia Evmenenko"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 337,
      "sutta/kn": 337,
      "sutta/kn/thag": 264,
      "sutta/kn/thig": 73
    }
  },
  "th:jayasaro": {
    "type": "translation",
    "lang": "th",
    "author": "jayasaro",
    "name": [
      "Jayasāro Bhikkhu"
    ],
    "exampleVersion": 0,
    "vinaya": true,
    "stats": {
      "vinaya": 2
    }
  },
  "lo:jayasaro": {
    "type": "translation",
    "lang": "lo",
    "author": "jayasaro",
    "name": [
      "Jayasāro Bhikkhu"
    ],
    "exampleVersion": 0,
    "vinaya": true,
    "stats": {
      "vinaya": 2
    }
  },
  "gsw:flavio": {
    "type": "translation",
    "lang": "gsw",
    "author": "flavio",
    "name": [
      "Flavio Stucky"
    ],
    "exampleVersion": 0,
    "sutta": true,
    "stats": {
      "sutta": 2,
      "sutta/kn": 2,
      "sutta/kn/kp": 1,
      "sutta/kn/snp": 1,
      "sutta/kn/snp/vagga1": 1
    }
  }
}

export default AUTHORS;
