#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

sudo npm install -g npm@latest
echo -e "${SCRIPT}: npm version `npm --version`"

npm install
